### ISSUE TITLE
Translations are not ideal

### ISSUE THREAD

**Issue by Diamanter** [HyvorTalk/hyvor-talk-wordpress-plugin#1]
I'm not happy with your russian translations. 
1. They break your layout (add nowrap or max-width for elements)
2. They are too english

Can I have a tool to set up translations (query string maybe)? Ideally I would like to change icons too.

![image](https://user-images.githubusercontent.com/5965690/84584565-32132480-ae30-11ea-810c-cc303d759c66.png)

**Comment by Hyvor** [comment]
Hello, 

Our translation process is completely run by the community. Please check [this faq](https://talk.hyvor.com/documentation/faq/translate-contribute) to learn more about it. You can submit a new version of the Russian translation there.

Thanks.

**Comment by Diamanter** [comment]
OK, thank you for answering on keyword "translation".
Some reaction on "please fix bug with the layout" and "need custom icons"? )

**Comment by Hyvor** [comment]
please fix bug with the layout - this is probably an issue with Russian translation. The Russian translation seems to be longer than English words. That's why it wraps down. And, we intentionally bring the overflowed icons down to avoid they going hidden out of the screen. I've forwarded this issue to our designer to check how we can fix it. Thanks for pointing out. 

need custom icons - we plan to add custom reactions very soon!

Please contact us via live chat or talk.support@hyvor.com if you need more help.
